version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_USERNAME=admin
      - REDIS_PASSWORD=admin
  
  accountservice:
    build: ./account/
    ports:
      - "8081:8080"
    depends_on:
      - redis
  
  notification:
    build: ./notification/
    ports:
      - "8082:8080"
    depends_on:
      - redis
    
  order:
    build: ./order/
    ports:
      - "8080:8080"
    depends_on:
      - redis